export const products = [
    {
        _id: 1,
        name: "Topi Keren",
        image: "https://res.cloudinary.com/tv-masa-kini/image/upload/v1626373390/online%20store/hat_n8ar6o.jpg",
        description:
            "ORIGINAL NEW WITH TAG, Garansi uang kembali jika terbukti palsu",
        brand: "MyBrand",
        category: "Topi",
        price: 250.001,
        countInStock: 3,
        rating: 3.5,
        numReviews: 4,
    },
    {
        _id: 2,
        name: "Jaket",
        image: "https://res.cloudinary.com/tv-masa-kini/image/upload/v1626373389/online%20store/mens_yqlmek.jpg",
        description:
            "ORIGINAL NEW WITH TAG, Garansi uang kembali jika terbukti palsu",
        brand: "MyBrand",
        category: "Jaket",
        price: 250.001,
        countInStock: 3,
        rating: 1.5,
        numReviews: 4,
    },
    {
        _id: 3,
        name: "Blazer keren",
        image: "https://res.cloudinary.com/tv-masa-kini/image/upload/v1626373389/online%20store/womens_oli3ix.jpg",
        description:
            "ORIGINAL NEW WITH TAG, Garansi uang kembali jika terbukti palsu",
        brand: "MyBrand",
        category: "Womens",
        price: 250.001,
        countInStock: 3,
        rating: 5,
        numReviews: 4,
    },
    {
        _id: 4,
        name: "Sneaker keren",
        image: "https://res.cloudinary.com/tv-masa-kini/image/upload/v1626373389/online%20store/sneakers_qc90wv.jpg",
        description:
            "ORIGINAL NEW WITH TAG, Garansi uang kembali jika terbukti palsu",
        brand: "MyBrand",
        category: "Sepatu",
        price: 250.001,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: 5,
        name: "Jam branded",
        image: "https://res.cloudinary.com/tv-masa-kini/image/upload/v1626371496/samples/ecommerce/analog-classic.jpg",
        description:
            "ORIGINAL NEW WITH TAG, Garansi uang kembali jika terbukti palsu",
        brand: "MyBrand",
        category: "Jam Tangan",
        price: 250.001,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: 6,
        name: "Jam branded",
        image: "https://res.cloudinary.com/tv-masa-kini/image/upload/v1626371496/samples/ecommerce/analog-classic.jpg",
        description:
            "ORIGINAL NEW WITH TAG, Garansi uang kembali jika terbukti palsu",
        brand: "MyBrand",
        category: "Jam Tangan",
        price: 250.001,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: 7,
        name: "Jam branded",
        image: "https://res.cloudinary.com/tv-masa-kini/image/upload/v1626371496/samples/ecommerce/analog-classic.jpg",
        description:
            "ORIGINAL NEW WITH TAG, Garansi uang kembali jika terbukti palsu",
        brand: "MyBrand",
        category: "Jam Tangan",
        price: 250.001,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: 8,
        name: "Jam branded",
        image: "https://res.cloudinary.com/tv-masa-kini/image/upload/v1626371496/samples/ecommerce/analog-classic.jpg",
        description:
            "ORIGINAL NEW WITH TAG, Garansi uang kembali jika terbukti palsu",
        brand: "MyBrand",
        category: "Jam Tangan",
        price: 250.001,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: 9,
        name: "Jam branded",
        image: "https://res.cloudinary.com/tv-masa-kini/image/upload/v1626371496/samples/ecommerce/analog-classic.jpg",
        description:
            "ORIGINAL NEW WITH TAG, Garansi uang kembali jika terbukti palsu",
        brand: "MyBrand",
        category: "Jam Tangan",
        price: 250.001,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: 10,
        name: "Jam branded",
        image: "https://res.cloudinary.com/tv-masa-kini/image/upload/v1626371496/samples/ecommerce/analog-classic.jpg",
        description:
            "ORIGINAL NEW WITH TAG, Garansi uang kembali jika terbukti palsu",
        brand: "MyBrand",
        category: "Jam Tangan",
        price: 250.001,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: 11,
        name: "Jam branded",
        image: "https://res.cloudinary.com/tv-masa-kini/image/upload/v1626371496/samples/ecommerce/analog-classic.jpg",
        description:
            "ORIGINAL NEW WITH TAG, Garansi uang kembali jika terbukti palsu",
        brand: "MyBrand",
        category: "Jam Tangan",
        price: 250.001,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: 12,
        name: "Jam branded",
        image: "https://res.cloudinary.com/tv-masa-kini/image/upload/v1626371496/samples/ecommerce/analog-classic.jpg",
        description:
            "ORIGINAL NEW WITH TAG, Garansi uang kembali jika terbukti palsu",
        brand: "MyBrand",
        category: "Jam Tangan",
        price: 250.001,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: 13,
        name: "Jam branded",
        image: "https://res.cloudinary.com/tv-masa-kini/image/upload/v1626371496/samples/ecommerce/analog-classic.jpg",
        description:
            "ORIGINAL NEW WITH TAG, Garansi uang kembali jika terbukti palsu",
        brand: "MyBrand",
        category: "Jam Tangan",
        price: 250.001,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
];
